Update CatBot_Selfbot.py
I had cloned this in my termux, but I got an Error sayd :
~/SelfbotLine $ python CatBot_Selfbot.py
  File "/data/data/com.termux/files/home/SelfbotLine/CatBot_Selfbot.py", line 12
    print "===[Login Success]==="
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("===[Login Success]===")?

So I propose to add () to the text ("===[Login Succes]==="). thanks